### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by svandragt** [foxxyz/sublime_alphpetize#11]
Not sure if I'm the only one, but on PHP files with Windows line endings, sorting methods results in superfluous <CR> blocks.

This disappears if I set windows to use \n;

Would make a pull request but perhaps it's a certain setting not being respected? Can anyone confirm?

**Comment by geoff-maddock** [comment]
Tried this out and I noticed this as well.  Using with sublime text 3 on windows.

Ends up with extraneous [CR] after the end curly, as well as a large empty block near the top of my class definition.   I'm guessing that is coming from extra empty lines between existing methods.

**Comment by foxxyz** [comment]
Will make some time to look at this next week, thanks for the notification!

**Comment by foxxyz** [comment]
Unfortunately I don't use windows anymore, so I don't have a reliable foundation to test this on. I'm closing this for now, but I would gladly review a pull request if anyone is interesting in fixing windows compatibility.
