### ISSUE TITLE
Empty line after and before class parenthesis

### ISSUE THREAD

**Issue by keevitaja** [foxxyz/sublime_alphpetize#14]
Plugin ads unwanted empty lines

```php
class A
{
    function test()
    {
    }
}
```

becomes 

```php
class A
{

    function test()
    {
    }

}
```

This kind of coding style does not follow PSR2

**Comment by foxxyz** [comment]
@keevitaja Thanks for the bug report! Let me know if you find anything else that's incompatible with PSR2.

**Comment by marmotz** [comment]
It seems that your fix cause a new problem.

I have this kind of code:
```php
<?php

namespace My\Namespace;

class Cursor
{
    /**
     * @var Object
     */
    protected $property1;
    
    /**
     * @var Object
     */
    protected $property2;

    /**
     * Constructor
     */
    public function __construct()
    {
        // do something
    }
}
```

It becomes:
```php
<?php

namespace My\Namespace;

class Cursor
{    /**
     * Constructor
     */
    public function __construct()
    {
        // do something
    }}
```

**Comment by keevitaja** [comment]
Well, then it does not support PSR2 as it excepts

```
class Bar {
```

https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md

**Comment by foxxyz** [comment]
@marmotz Thank you for reporting - this was an oversight on my part and should be fixed now.

**Comment by foxxyz** [comment]
@keevitaja I'm not sure I understand. Are you saying that Alphpetize should correct class declarations from single-line to multi-line?

**Comment by marmotz** [comment]
@foxxyz Sublime doesn't upgrade alphpetize to the last version. 
Or it's still bugged.
Even if I remove/reinstall package.

**Comment by marmotz** [comment]
and unit tests doesn't work on ST3 :-/
